# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'managenetgui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(876, 686)
        MainWindow.setMinimumSize(QtCore.QSize(876, 686))
        MainWindow.setMaximumSize(QtCore.QSize(876, 686))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(876, 666))
        self.centralwidget.setMaximumSize(QtCore.QSize(876, 666))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.btnOpen = QtGui.QPushButton(self.centralwidget)
        self.btnOpen.setGeometry(QtCore.QRect(80, 10, 40, 40))
        self.btnOpen.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpen.setIcon(icon)
        self.btnOpen.setIconSize(QtCore.QSize(30, 30))
        self.btnOpen.setObjectName(_fromUtf8("btnOpen"))
        self.btnSave = QtGui.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(130, 10, 40, 40))
        self.btnSave.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon1)
        self.btnSave.setIconSize(QtCore.QSize(30, 30))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.graphView = QtGui.QGraphicsView(self.centralwidget)
        self.graphView.setGeometry(QtCore.QRect(80, 70, 600, 600))
        self.graphView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.graphView.setMouseTracking(True)
        self.graphView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.graphView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphView.setDragMode(QtGui.QGraphicsView.NoDrag)
        self.graphView.setObjectName(_fromUtf8("graphView"))
        self.btnAddNode = QtGui.QPushButton(self.centralwidget)
        self.btnAddNode.setGeometry(QtCore.QRect(20, 120, 40, 40))
        self.btnAddNode.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/add_node.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddNode.setIcon(icon2)
        self.btnAddNode.setIconSize(QtCore.QSize(30, 30))
        self.btnAddNode.setObjectName(_fromUtf8("btnAddNode"))
        self.btnDeleteNode = QtGui.QPushButton(self.centralwidget)
        self.btnDeleteNode.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.btnDeleteNode.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/delete_node.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeleteNode.setIcon(icon3)
        self.btnDeleteNode.setIconSize(QtCore.QSize(30, 30))
        self.btnDeleteNode.setObjectName(_fromUtf8("btnDeleteNode"))
        self.btnAddEdge = QtGui.QPushButton(self.centralwidget)
        self.btnAddEdge.setGeometry(QtCore.QRect(20, 220, 40, 40))
        self.btnAddEdge.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/add_edge.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddEdge.setIcon(icon4)
        self.btnAddEdge.setIconSize(QtCore.QSize(30, 30))
        self.btnAddEdge.setObjectName(_fromUtf8("btnAddEdge"))
        self.btnDeleteEdge = QtGui.QPushButton(self.centralwidget)
        self.btnDeleteEdge.setGeometry(QtCore.QRect(20, 270, 40, 40))
        self.btnDeleteEdge.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/delete_edge.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeleteEdge.setIcon(icon5)
        self.btnDeleteEdge.setIconSize(QtCore.QSize(30, 30))
        self.btnDeleteEdge.setObjectName(_fromUtf8("btnDeleteEdge"))
        self.btnMoveNode = QtGui.QPushButton(self.centralwidget)
        self.btnMoveNode.setGeometry(QtCore.QRect(20, 70, 40, 40))
        self.btnMoveNode.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMoveNode.setIcon(icon6)
        self.btnMoveNode.setIconSize(QtCore.QSize(30, 30))
        self.btnMoveNode.setObjectName(_fromUtf8("btnMoveNode"))
        self.btnClear = QtGui.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(180, 10, 40, 40))
        self.btnClear.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClear.setIcon(icon7)
        self.btnClear.setIconSize(QtCore.QSize(30, 30))
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.lblXY = QtGui.QLineEdit(self.centralwidget)
        self.lblXY.setEnabled(False)
        self.lblXY.setGeometry(QtCore.QRect(570, 50, 110, 20))
        self.lblXY.setObjectName(_fromUtf8("lblXY"))
        self.groupNode = QtGui.QGroupBox(self.centralwidget)
        self.groupNode.setGeometry(QtCore.QRect(700, 70, 151, 261))
        self.groupNode.setObjectName(_fromUtf8("groupNode"))
        self.chkShowRadius = QtGui.QCheckBox(self.groupNode)
        self.chkShowRadius.setGeometry(QtCore.QRect(50, 230, 81, 17))
        self.chkShowRadius.setObjectName(_fromUtf8("chkShowRadius"))
        self.lblId = QtGui.QLineEdit(self.groupNode)
        self.lblId.setEnabled(False)
        self.lblId.setGeometry(QtCore.QRect(20, 30, 21, 20))
        self.lblId.setObjectName(_fromUtf8("lblId"))
        self.lblCommRange = QtGui.QLineEdit(self.groupNode)
        self.lblCommRange.setEnabled(False)
        self.lblCommRange.setGeometry(QtCore.QRect(20, 170, 113, 20))
        self.lblCommRange.setObjectName(_fromUtf8("lblCommRange"))
        self.lblX = QtGui.QLineEdit(self.groupNode)
        self.lblX.setEnabled(False)
        self.lblX.setGeometry(QtCore.QRect(20, 100, 21, 20))
        self.lblX.setObjectName(_fromUtf8("lblX"))
        self.spinId = QtGui.QSpinBox(self.groupNode)
        self.spinId.setGeometry(QtCore.QRect(50, 30, 71, 22))
        self.spinId.setMaximum(10000)
        self.spinId.setObjectName(_fromUtf8("spinId"))
        self.spinCommRange = QtGui.QDoubleSpinBox(self.groupNode)
        self.spinCommRange.setGeometry(QtCore.QRect(50, 200, 71, 22))
        self.spinCommRange.setMaximum(10000.0)
        self.spinCommRange.setSingleStep(10.0)
        self.spinCommRange.setObjectName(_fromUtf8("spinCommRange"))
        self.lblY = QtGui.QLineEdit(self.groupNode)
        self.lblY.setEnabled(False)
        self.lblY.setGeometry(QtCore.QRect(20, 130, 21, 20))
        self.lblY.setObjectName(_fromUtf8("lblY"))
        self.spinY = QtGui.QDoubleSpinBox(self.groupNode)
        self.spinY.setGeometry(QtCore.QRect(50, 130, 71, 22))
        self.spinY.setMinimum(0.0)
        self.spinY.setMaximum(1000.0)
        self.spinY.setObjectName(_fromUtf8("spinY"))
        self.spinX = QtGui.QDoubleSpinBox(self.groupNode)
        self.spinX.setGeometry(QtCore.QRect(50, 100, 71, 22))
        self.spinX.setMinimum(0.0)
        self.spinX.setMaximum(1000.0)
        self.spinX.setSingleStep(1.0)
        self.spinX.setObjectName(_fromUtf8("spinX"))
        self.lblNodePos = QtGui.QLineEdit(self.groupNode)
        self.lblNodePos.setEnabled(False)
        self.lblNodePos.setGeometry(QtCore.QRect(20, 70, 111, 20))
        self.lblNodePos.setObjectName(_fromUtf8("lblNodePos"))
        self.groupEnv = QtGui.QGroupBox(self.centralwidget)
        self.groupEnv.setGeometry(QtCore.QRect(700, 340, 151, 201))
        self.groupEnv.setObjectName(_fromUtf8("groupEnv"))
        self.btnOpenEnv = QtGui.QPushButton(self.groupEnv)
        self.btnOpenEnv.setGeometry(QtCore.QRect(90, 20, 40, 40))
        self.btnOpenEnv.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/all_icons/open_env.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenEnv.setIcon(icon8)
        self.btnOpenEnv.setIconSize(QtCore.QSize(30, 30))
        self.btnOpenEnv.setObjectName(_fromUtf8("btnOpenEnv"))
        self.lblEnvSize = QtGui.QLineEdit(self.groupEnv)
        self.lblEnvSize.setEnabled(False)
        self.lblEnvSize.setGeometry(QtCore.QRect(20, 70, 111, 20))
        self.lblEnvSize.setObjectName(_fromUtf8("lblEnvSize"))
        self.lblEnvX = QtGui.QLineEdit(self.groupEnv)
        self.lblEnvX.setEnabled(False)
        self.lblEnvX.setGeometry(QtCore.QRect(20, 100, 21, 20))
        self.lblEnvX.setObjectName(_fromUtf8("lblEnvX"))
        self.lblEnvY = QtGui.QLineEdit(self.groupEnv)
        self.lblEnvY.setEnabled(False)
        self.lblEnvY.setGeometry(QtCore.QRect(20, 130, 21, 20))
        self.lblEnvY.setObjectName(_fromUtf8("lblEnvY"))
        self.spinEnvY = QtGui.QDoubleSpinBox(self.groupEnv)
        self.spinEnvY.setGeometry(QtCore.QRect(50, 130, 71, 22))
        self.spinEnvY.setMinimum(0.0)
        self.spinEnvY.setMaximum(1000.0)
        self.spinEnvY.setObjectName(_fromUtf8("spinEnvY"))
        self.spinEnvX = QtGui.QDoubleSpinBox(self.groupEnv)
        self.spinEnvX.setGeometry(QtCore.QRect(50, 100, 71, 22))
        self.spinEnvX.setMinimum(0.0)
        self.spinEnvX.setMaximum(1000.0)
        self.spinEnvX.setSingleStep(10.0)
        self.spinEnvX.setObjectName(_fromUtf8("spinEnvX"))
        self.chkShowEnv = QtGui.QCheckBox(self.groupEnv)
        self.chkShowEnv.setGeometry(QtCore.QRect(20, 170, 121, 17))
        self.chkShowEnv.setChecked(True)
        self.chkShowEnv.setObjectName(_fromUtf8("chkShowEnv"))
        self.lblOpenEnv = QtGui.QLineEdit(self.groupEnv)
        self.lblOpenEnv.setEnabled(False)
        self.lblOpenEnv.setGeometry(QtCore.QRect(20, 30, 61, 20))
        self.lblOpenEnv.setObjectName(_fromUtf8("lblOpenEnv"))
        self.groupChanType = QtGui.QGroupBox(self.centralwidget)
        self.groupChanType.setGeometry(QtCore.QRect(700, 550, 151, 121))
        self.groupChanType.setObjectName(_fromUtf8("groupChanType"))
        self.chkAutoAddEdge = QtGui.QCheckBox(self.groupChanType)
        self.chkAutoAddEdge.setGeometry(QtCore.QRect(20, 60, 111, 51))
        self.chkAutoAddEdge.setChecked(True)
        self.chkAutoAddEdge.setObjectName(_fromUtf8("chkAutoAddEdge"))
        self.comboChannelType = QtGui.QComboBox(self.groupChanType)
        self.comboChannelType.setGeometry(QtCore.QRect(10, 30, 121, 22))
        self.comboChannelType.setObjectName(_fromUtf8("comboChannelType"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupNode.setTitle(_translate("MainWindow", "Node info", None))
        self.chkShowRadius.setText(_translate("MainWindow", "show range", None))
        self.lblId.setText(_translate("MainWindow", "Id:", None))
        self.lblCommRange.setText(_translate("MainWindow", "Communication range:", None))
        self.lblX.setText(_translate("MainWindow", "x:", None))
        self.lblY.setText(_translate("MainWindow", "y:", None))
        self.lblNodePos.setText(_translate("MainWindow", "Node position:", None))
        self.groupEnv.setTitle(_translate("MainWindow", "Environment info", None))
        self.lblEnvSize.setText(_translate("MainWindow", "Environment size:", None))
        self.lblEnvX.setText(_translate("MainWindow", "x:", None))
        self.lblEnvY.setText(_translate("MainWindow", "y:", None))
        self.chkShowEnv.setText(_translate("MainWindow", "show environment", None))
        self.lblOpenEnv.setText(_translate("MainWindow", "Open env:", None))
        self.groupChanType.setTitle(_translate("MainWindow", "Model of communication", None))
        self.chkAutoAddEdge.setText(_translate("MainWindow", "USE MODEL OF \n"
"COMMUNICATON \n"
"TO AUTO EDGES", None))

import icons_rc
